default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: book_review

test:
  <<: *default
  database: book_review_test

production:
  <<: *default
  database: book_review_production
  username: root
  password:
