user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
review:
  max_length: 140
comment:
  max_length: 140
book:
  max_length: 50
book_index: "250x350"
book_show: "325x475"
helpers:
  user:
    size: 80
controllers:
  book:
    index_page: 3
models:
  limit: 4
controller:
  sessions: "1"
